# Clippy configuration for polyfill-rs
# Modern configuration format for production

# Complexity thresholds
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 7
too-many-lines-threshold = 150
type-complexity-threshold = 250

# Size limits
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
large-error-threshold = 128

# Naming
single-char-binding-names-threshold = 4
enum-variant-name-threshold = 3

# Performance and safety
avoid-breaking-exported-api = false
check-private-items = true

# Documentation
missing-docs-in-crate-items = true

# Allow certain patterns common in HFT code
allowed-idents-below-min-chars = ["id", "tx", "rx", "ok", "io", "db", "ws", "ts", "ms", "us", "ns"]

# Third-party crates where we allow more lenient rules
third-party = ["serde", "tokio", "alloy"] 